# Generated by Django 5.0.1 on 2024-03-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupe', '0001_initial'),
        ('grupe1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupe1',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupe', to='grupe.grupe'),
        ),
    ]
